oidc-node:
  build: .
  environment:
    - NODE_ENV=production
#    - NODE_PORT=8080
#    - OIDC_ISS=localhost:8080
  links:
    - redis
  ports:
    - "8080:8080"
redis:
  image: redis
  ports:
    - "6379"
