@startuml

actor Alice
participant BrowserA as brwa
participant IdPProxy as proxyA
participant "https://IdPA" as idp
participant IdPProxy as proxyB
participant BrowserB as brwb
actor Bob

== Initial login ==
Alice	-> 	idp			: Login
idp		->	brwa 		: cookie@idpa

== WebRTC Generate Assertion ==
note right of Alice
	client JS code call setIdentityProvider(DOMAIN, PROTOCOL)
	during webrtc communication setup.
end note

brwa	-> idp			: GET /.well-known/idp-proxy/PROTOCOL
idp 	-> brwa			: 200 proxy.js

create proxyA
brwa	--> proxyA 		: <<Create>>
note right of brwa
	Proxy is sandboxed by browser
end note

proxyA	-> idp			: GET /proxy/key
idp		-> proxyA		: 200 KEY
brwa 	-> proxyA		: generateAssertion(CONTENTS)
note right of proxyA
	Contents contains fingerprint
	of each SDP certificates
end note

proxyA	-> idp			: /proxy/authorize?
note right of idp
	?scope=openid webrtc&client_id=KEY
    &redirect_uri=/proxy/done&response_type=id_token token
	&nonce='N-'+Math.random()&rtcsdp=+btoa(CONTENTS)
	
	redirect is not used with scope webrtc as I'm not able to retrieve
	ID_TOKEN in returned fragment. So it is returned in body.
end note

idp 	->	proxyA		: 200 ID_TOKEN
note right of proxyA
	{ "typ": "JWT",
	  "alg": "RS256"}.
	{ "iss": "https://IdPA",
	  "sub": "bob@idp.com",
	  "aud": KEY,
	  "exp": 1456935997,"iat": 1456932397,
	  "nonce": "N-0.7719116394994261",
	  "rtcsdp": btoa(CONTENTS),
	  "at_hash": "RzRNTwdSJUUFMGZvFUFKSw"}.
	 SIGNATURE
end note

proxyA	->	brwa		: resolve(ID_ASSERTION)
note right of brwa
	{assertion: ID_TOKEN,
	 idp: {domain: DOMAIN,
	 	   protocol: PROTOCOL}}
end note

brwa 	-> brwb			: SDP with a=identity:ID_ASSERTION

== WebRTC Validate Assertion ==
brwb	-> idp			: GET /.well-known.idp-proxy/PROTOCOL
idp		-> brwb			: 200 proxy.js

create proxyB
brwb	--> proxyB		: <<Create>>
note right of proxyB
	IdP Proxy is sandboxed by browser
end note
proxyB	-> idp 			: GET /proxy/key
idp		-> proxyB		: 200 KEY
brwb	-> proxyB		: validateAssertion(ID_TOKEN)
proxyB	-> proxyB		: verify ID_TOKEN with Key
proxyB	-> brwb			: Resolve(IDENTITY)
note right of brwb
	{identity: USERNAME@DOMAIN,
	 contents: CONTENTS}
end note

@enduml